In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np  # linear algebra
import pandas as pd  # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

# for dirname, _, filenames in os.walk("/kaggle/input"):
# for filename in filenames:
# print(os.path.join(dirname, filenames))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub

# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
# !pip install jupyter-black
# %load_ext jupyter_black

In [3]:
TRAIN_LABELS_PATH = (
    "/kaggle/input/competitions/soil-grain-size-from-photos/Training_labels_updated.csv"
)
TRAIN_PPM_PATH = (
    "/kaggle/input/competitions/soil-grain-size-from-photos/ppm_updated.csv"
)

TRAIN_IMG_PATH = "/kaggle/input/competitions/soil-grain-size-from-photos/Training-All_Photos_updated/Training-All_Photos_updated"
TEST_IMG_PATH = "/kaggle/input/competitions/soil-grain-size-from-photos/Test_All_Photos/Test_All_Photos"
SAMPLE_SUB_PATH = (
    "/kaggle/input/competitions/soil-grain-size-from-photos/sample_submission.csv"
)

In [4]:
df_labels = pd.read_csv(TRAIN_LABELS_PATH)
df_ppm = pd.read_csv(TRAIN_PPM_PATH)
df_labels.shape, df_ppm.shape

((24, 12), (5, 5))

In [5]:
df_labels.head()

,sample_id,0.002,0.0063,0.02,0.063,0.2,0.63,2,6.3,20,63,200
0,F827,9.4904,19.3892,47.6257,89.5554,99.8965,99.9896,100.0000,100.0000,100.0000,100.0000,100.0
1,G190,5.2076,10.2425,23.7537,50.3113,75.8311,85.7233,90.9898,94.8969,98.5814,100.0000,100.0
2,H030,6.7833,10.9091,19.0599,37.3235,66.8349,96.4965,97.9530,99.5691,100.0000,100.0000,100.0
3,H037,0.9320,6.4500,16.3216,27.8019,34.6629,46.3652,62.7168,79.0523,89.7830,100.0000,100.0
4,H038,1.8218,5.1400,10.6113,18.2778,24.6420,35.0767,47.2345,63.3992,81.0851,95.7127,100.0

In [6]:
df_ppm.head()

                     phone                   camera  width  height     ppm
0                iPhone 14                iPhone 14   4032    3024  13.942
1                iPhone 16                iPhone 16   5712    4284  19.525
2            Motorola Edge         motorola edge 20   4000    1800  11.492
3  Motorola Edge 60 Fusion  Motorola Edge 60 fusion   4096    2304  12.465
4              Samsung A52                 SM-A525F   9248    6936  26.330

In [7]:
camera_metadata = {}
mean_ppm = df_ppm['ppm'].mean()
std_ppm = df_ppm['ppm'].std()
print(f'mean ppm = {mean_ppm} and std ppm = {std_ppm}')

for _, row in df_ppm.iterrows():
    camera_metadata[row["phone"]] = {
        "aspect_ratio": row["width"] / row["height"],
        "ppm": (row["ppm"] - mean_ppm) / std_ppm
    }

camera_metadata

mean ppm = 16.7508 and std ppm = 6.192125539748043

{'iPhone 14': {'aspect_ratio': 1.3333333333333333,
  'ppm': np.float64(-0.4536083743732191)},
 'iPhone 16': {'aspect_ratio': 1.3333333333333333,
  'ppm': np.float64(0.44802063236477585)},
 'Motorola Edge': {'aspect_ratio': 2.2222222222222223,
  'ppm': np.float64(-0.8492721871097564)},
 'Motorola Edge 60 Fusion': {'aspect_ratio': 1.7777777777777777,
  'ppm': np.float64(-0.6921371300515317)},
 'Samsung A52': {'aspect_ratio': 1.3333333333333333,
  'ppm': np.float64(1.5469970591697295)}}

In [8]:
for s in os.listdir(TRAIN_IMG_PATH)[:5]:
    split = s.split("_")
    prefix, _id, suffix = "".join(split[:-2]), split[-2], split[-1]
    print(prefix, _id, suffix)

SamsungA52 H666 01.jpg
MotorolaEdge60fusion H374 02.jpg
MotorolaEdge60fusion H374 03.jpg
MotorolaEdge H368 04.jpg
SamsungA52 H038 01.jpg

In [9]:
mobile_img = {}

for s in os.listdir(TRAIN_IMG_PATH):
    split = s.split("_")
    prefix, _id, suffix = "_".join(split[:-2]), split[-2], split[-1]
    key = prefix + "_" + _id
    if key in mobile_img:
        mobile_img[key].append(s)
    else:
        mobile_img[key] = [s]

In [10]:
len(mobile_img), mobile_img["Motorola_Edge_60_fusion_H374"], mobile_img[
    "Motorola_Edge_H368"
]

(45,
 ['Motorola_Edge_60_fusion_H374_02.jpg',
  'Motorola_Edge_60_fusion_H374_03.jpg',
  'Motorola_Edge_60_fusion_H374_01.jpg'],
 ['Motorola_Edge_H368_04.jpg',
  'Motorola_Edge_H368_02.jpg',
  'Motorola_Edge_H368_03.jpg',
  'Motorola_Edge_H368_01.jpg'])

In [11]:
for s in os.listdir(TRAIN_IMG_PATH):
    split = s.split("_")
    prefix, _id, suffix = "".join(split[:-2]), split[-2], split[-1]
    if _id == "H666":
        print(prefix, _id, suffix)

SamsungA52 H666 01.jpg
MotorolaEdge H666 03.jpg
MotorolaEdge H666 02.jpg
MotorolaEdge H666 01.jpg

## Same soil img taken by different cameras above cell

In [12]:
from torch.utils.data import Dataset, DataLoader
import torch
from PIL import Image
from pathlib import Path
from collections import defaultdict
import re

In [13]:
class SoilDataset(Dataset):
    def __init__(self, image_dir, labels_df, transform=None):
        self.image_dir = Path(image_dir)
        self.transform = transform

        self.labels = labels_df.set_index("sample_id")

        # sample_id -> image paths
        self.sample_to_images = defaultdict(list)

        # mobile_img and camera_metadata are already defined globally
        for key, suffixes in mobile_img.items():
            arr = key.split("_")
            camera = f"{arr[0]} {arr[1]}"
            sample_id = arr[-1]
            # if camera not in camera_metadata:
            #     print(camera, sample_id)

            for suffix in suffixes:
                image_path = self.image_dir / suffix
                self.sample_to_images[sample_id].append((image_path, camera))

        # Only keep samples present in this dataframe
        self.sample_ids = [
            sample_id
            for sample_id in self.labels.index
            if sample_id in self.sample_to_images
        ]

    def __len__(self):
        return len(self.sample_ids)

    def __getitem__(self, idx):
        sample_id = self.sample_ids[idx]
        image_paths = self.sample_to_images[sample_id]
        images = []
        cameras = []

        for image_path, camera in image_paths:
            image = Image.open(image_path).convert("RGB")
            if self.transform is not None:
                image = self.transform(image)
            images.append(image)
            cameras.append(camera)

        # [N_images, C, H, W]
        images = torch.stack(images)
        # [N_images, 2]
        metadata = torch.tensor(
            [
                [
                    camera_metadata[camera]["ppm"],
                    camera_metadata[camera]["aspect_ratio"],
                ]
                for camera in cameras
            ],
            dtype=torch.float32,
        )
        # [11]
        target = torch.tensor(self.labels.loc[sample_id].values, dtype=torch.float32)

        return {
            "sample_id": sample_id,
            "cameras": cameras,
            "metadata": metadata,
            "images": images,
            "target": target,
        }

In [14]:
sample_sub_df = pd.read_csv(SAMPLE_SUB_PATH)

sample_ids = []

for filename in os.listdir(TEST_IMG_PATH):

    name = os.path.splitext(filename)[0]

    # Remove image number at the end: (1), (2), ...
    name = re.sub(r"\s*\(\d+\)$", "", name)

    # Remove camera prefix
    name = re.sub(r"^iPhone14_", "", name)
    name = re.sub(r"^iPhone16_", "", name)
    name = re.sub(r"^iPhone_16_", "", name)

    # Match submission naming
    name = name.replace("HPC_Münster_BS6_9,0-10m", "HPC_Muenster_BS6_9_0-10m")

    sample_ids.append(name)

sample_ids = sorted(set(sample_ids))

In [15]:
sample_ids_set = set(sample_ids)
submission_ids_set = set(sample_sub_df["sample_id"])

print("In sample_ids but NOT in submission:")
print(sample_ids_set - submission_ids_set)

print("\nIn submission but NOT in sample_ids:")
print(submission_ids_set - sample_ids_set)

print("\nAll sample_ids present:", sample_ids_set <= submission_ids_set)
print("Same IDs:", sample_ids_set == submission_ids_set)

In sample_ids but NOT in submission:
set()

In submission but NOT in sample_ids:
set()

All sample_ids present: True
Same IDs: True

In [16]:
def parse_test_filename(image_path):
    """
    Example:
        iPhone16_HPC_Airbus BS10-4bis7 (2).JPG
        ->
        camera    = iPhone16
        sample_id = HPC_Airbus BS10-4bis7
    """
    name = Path(image_path).stem

    # Remove (1), (2), ... from the end
    name = re.sub(r"\s*\(\d+\)$", "", name)

    # Remove camera prefix
    if name.startswith("iPhone14_"):
        camera = "iPhone 14"
        sample_id = name[len("iPhone14_") :]

    elif name.startswith("iPhone16_"):
        camera = "iPhone 16"
        sample_id = name[len("iPhone16_") :]

    elif name.startswith("iPhone_16_"):
        camera = "iPhone 16"
        sample_id = name[len("iPhone_16_") :]

    else:
        # Useful for other cameras if they appear
        camera, sample_id = name.split("_", 1)

    # Match sample_submission naming
    sample_id = sample_id.replace("HPC_Münster_BS6_9,0-10m", "HPC_Muenster_BS6_9_0-10m")

    return camera, sample_id

In [17]:
class SoilTestDataset(Dataset):
    def __init__(self, image_dir, transform=None):
        self.image_dir = Path(image_dir)
        self.transform = transform

        # sample_id -> list of image paths
        self.sample_to_images = defaultdict(list)

        # Parse all images
        for image_path in sorted(self.image_dir.iterdir()):
            # did not use camera for now
            camera, sample_id = parse_test_filename(image_path)
            # print(camera)
            self.sample_to_images[sample_id].append((image_path, camera))

        # One dataset item = one soil sample
        self.sample_ids = sorted(self.sample_to_images.keys())

    def __len__(self):
        return len(self.sample_ids)

    def __getitem__(self, idx):
        sample_id = self.sample_ids[idx]

        image_data = self.sample_to_images[sample_id]

        images = []
        cameras = []
        metadata = []
        image_paths = []

        for image_path, camera in image_data:
            image = Image.open(image_path).convert("RGB")
            if self.transform is not None:
                image = self.transform(image)
            images.append(image)
            cameras.append(camera)
            image_paths.append(str(image_path))

            metadata.append(
                [
                    camera_metadata[camera]["ppm"],
                    camera_metadata[camera]["aspect_ratio"],
                ]
            )

        # N_images x C x H x W
        images = torch.stack(images)
        # N_images, 2
        metadata = torch.tensor(metadata, dtype=torch.float32)

        return {
            "sample_id": sample_id,
            "images": images,
            "cameras": cameras,
            "metadata": metadata,
            "image_paths": image_paths,
        }

In [18]:
from torchvision import transforms

from sklearn.model_selection import train_test_split

In [19]:
IMG_SIZE = 384

train_transform = transforms.Compose(
    [
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.5),
        transforms.RandomRotation(degrees=15),
        transforms.ColorJitter(
            brightness=0.15, contrast=0.15, saturation=0.10, hue=0.03
        ),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)


test_val_transform = transforms.Compose(
    [
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]
)


# test_transform = val_transform

In [20]:
train_df, val_df = train_test_split(
    df_labels, test_size=0.2, random_state=42, shuffle=True
)
train_df.shape, val_df.shape

((19, 12), (5, 12))

In [21]:
temp = SoilDataset(TRAIN_IMG_PATH, train_df, train_transform).__getitem__(0)
print(temp["sample_id"], temp["metadata"], temp["cameras"])

temp = SoilTestDataset(image_dir=TEST_IMG_PATH, transform=test_val_transform).__getitem__(0)
print(temp["sample_id"], temp["cameras"], temp["metadata"])
del temp

H367 tensor([[-0.8493,  2.2222],
        [-0.8493,  2.2222],
        [-0.8493,  2.2222],
        [ 1.5470,  1.3333]]) ['Motorola Edge', 'Motorola Edge', 'Motorola Edge', 'Samsung A52']
HPC_Airbus BS10-4bis7 ['iPhone 16', 'iPhone 16', 'iPhone 16'] tensor([[0.4480, 1.3333],
        [0.4480, 1.3333],
        [0.4480, 1.3333]])

In [22]:
train_dataset = SoilDataset(TRAIN_IMG_PATH, train_df, train_transform)
val_dataset = SoilDataset(TRAIN_IMG_PATH, val_df, test_val_transform)
test_dataset = SoilTestDataset(image_dir=TEST_IMG_PATH, transform=test_val_transform)

In [23]:
BATCH_SIZE = 1  # cause one id may have multiple images

train_loader = DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True
)
val_loader = DataLoader(
    val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True
)
test_loader = DataLoader(
    test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True
)

In [25]:
len(train_loader), len(val_loader), len(test_loader)

(19, 5, 10)

In [26]:
from torchvision.models import efficientnet_v2_s, EfficientNet_V2_S_Weights
# from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
import torch.nn as nn

In [27]:
class SoilModel(nn.Module):
    def __init__(self):
        super().__init__()

        weights = EfficientNet_V2_S_Weights.DEFAULT
        self.backbone = efficientnet_v2_s(weights=weights)

        feature_dim = self.backbone.classifier[1].in_features

        self.backbone.classifier = nn.Identity()

        # caemra metadata
        self.metadata_net = nn.Sequential(
            nn.Linear(2, 32),
            nn.ReLU(),
            nn.Linear(32, 32)
        )
        
        # +2 for aspect_ratio and ppm
        combined_dim = feature_dim + 32

        # Learn importance of each image
        self.attention = nn.Sequential(
            nn.Linear(combined_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )
        # Final prediction head
        # self.head = nn.Sequential(
        #     nn.Linear(combined_dim, 256),
        #     nn.ReLU(),
        #     nn.Dropout(0.5),
        #     nn.Linear(256, 11)
        # )
    
    def forward(self, x, metadata):
        B, N, C, H, W = x.shape

        # let say b=1,n=4
        # 4, 3, IMG_SIZE, IMG_SIZE
        x = x.view(B * N, C, H, W)

        # 4, 1280(efficient_net)
        x = self.backbone(x)
        # seperate out images (1, 4, 1280)
        x = x.view(B, N, -1)

        # Aggregate images belonging to same soil sample
        metadata = self.metadata_net(metadata)
        # [B, 1280 + 32]
        x = torch.cat([x, metadata], dim=-1)
        # [B, N, 1]
        attention_scores = self.attention(x)
        attention_weights = torch.softmax(
            attention_scores,
            dim=1
        )

        # x : [B, N, 1280 + 32]
        # attention_weights: [B, N, 1]
        # res -> [B, N, 1280 + 32]
        x = x * attention_weights
        # B,1280 + 32
        x = x.sum(dim=1)

        # [B, 11]
        # return self.head(x)
        # [B, 1280 + 32]
        return x

In [28]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SoilModel().to(device)

model.head, device

Downloading: "https://download.pytorch.org/models/efficientnet_v2_s-dd5fe13b.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_v2_s-dd5fe13b.pth

100%|██████████| 82.7M/82.7M [00:00<00:00, 169MB/s]

(Sequential(
   (0): Linear(in_features=1312, out_features=256, bias=True)
   (1): ReLU()
   (2): Dropout(p=0.5, inplace=False)
   (3): Linear(in_features=256, out_features=11, bias=True)
 ),
 device(type='cuda'))

In [29]:
def emd_loss(logits, target):
    grain_sizes = torch.tensor(
        [0.002, 0.0063, 0.02, 0.063, 0.2, 0.63, 2.0, 6.3, 20.0, 63.0, 200.0],
        dtype=logits.dtype,
        device=logits.device,
    )

    log_x = torch.log10(grain_sizes)

    dx = log_x[1:] - log_x[:-1]

    # logits -> positive bin masses
    mass = torch.softmax(logits, dim=-1)

    # masses -> cumulative distribution
    pred_cdf = torch.cumsum(mass, dim=-1) * 100.0

    # Difference between CDFs
    diff = torch.abs(pred_cdf[:, 1:] - target[:, 1:])

    # Weighted EMD
    loss = (diff * dx.unsqueeze(0)).sum(dim=-1)

    return loss.mean()

In [30]:
for param in model.backbone.parameters():
    param.requires_grad = False

for param in model.backbone.features[-2:].parameters():
    param.requires_grad = True

optimizer = torch.optim.AdamW(
    [
        {
            "params": model.backbone.features[-2:].parameters(),
            "lr": 1e-5
        },
        {
            "params": model.metadata_net.parameters(),
            "lr": 1e-3
        },
        {
            "params": model.attention.parameters(),
            "lr": 1e-3
        },
        {
            "params": model.head.parameters(),
            "lr": 1e-3
        },
    ],
    weight_decay=1e-4
)

In [31]:
total = sum(p.numel() for p in model.backbone.parameters())

trainable = sum(
    p.numel()
    for p in model.backbone.parameters()
    if p.requires_grad
)

print(f"Total:     {total:,}")
print(f"Trainable: {trainable:,}")

Total:     20,177,488
Trainable: 14,892,072

In [32]:
def train_one_epoch(model, loader, optimizer, device):
    model.train()

    running_loss = 0.0

    for batch in loader:
        images = batch["images"].to(device, non_blocking=True)
        target = batch["target"].to(device, non_blocking=True)
        metadata = batch["metadata"].to(device)

        optimizer.zero_grad()

        # [B, 11]
        logits = model(images, metadata)
        loss = emd_loss(logits, target)
        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    return running_loss / len(loader)

In [33]:
@torch.no_grad()
def validate(model, loader, device):
    model.eval()

    running_loss = 0.0
    for batch in loader:
        images = batch["images"].to(device)
        target = batch["target"].to(device)
        metadata = batch["metadata"].to(device)

        logits = model(images, metadata)
        loss = emd_loss(logits, target)

        running_loss += loss.item()

    return running_loss / len(loader)

In [47]:
from sklearn.linear_model import Ridge

In [34]:
num_epochs = 20

best_val_loss = float("inf")

for epoch in range(num_epochs):

    train_loss = train_one_epoch(model, train_loader, optimizer, device)
    val_loss = validate(model, val_loader, device)

    print(
        f"Epoch [{epoch+1:02d}/{num_epochs}] "
        f"Train EMD: {train_loss:.4f} | "
        f"Val EMD: {val_loss:.4f}"
    )

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_soil_model.pth")
        print("  -> saved best model")

Epoch [01/20] Train EMD: 92.3598 | Val EMD: 110.3735
  -> saved best model
Epoch [02/20] Train EMD: 92.4453 | Val EMD: 102.6698
  -> saved best model
Epoch [03/20] Train EMD: 81.0848 | Val EMD: 101.3464
  -> saved best model
Epoch [04/20] Train EMD: 80.3526 | Val EMD: 101.8047
Epoch [05/20] Train EMD: 83.6807 | Val EMD: 100.2511
  -> saved best model
Epoch [06/20] Train EMD: 80.5314 | Val EMD: 102.3669
Epoch [07/20] Train EMD: 79.7567 | Val EMD: 101.7392
Epoch [08/20] Train EMD: 80.7776 | Val EMD: 102.1978
Epoch [09/20] Train EMD: 82.8192 | Val EMD: 102.2677
Epoch [10/20] Train EMD: 79.4759 | Val EMD: 102.5041
Epoch [11/20] Train EMD: 87.6034 | Val EMD: 102.0561
Epoch [12/20] Train EMD: 76.1454 | Val EMD: 101.8623
Epoch [13/20] Train EMD: 81.3060 | Val EMD: 102.6772
Epoch [14/20] Train EMD: 81.1705 | Val EMD: 102.8716
Epoch [15/20] Train EMD: 77.2542 | Val EMD: 104.9305
Epoch [16/20] Train EMD: 68.4264 | Val EMD: 99.5932
  -> saved best model
Epoch [17/20] Train EMD: 72.2796 | Val EMD: 96.4139
  -> saved best model
Epoch [18/20] Train EMD: 83.7809 | Val EMD: 99.2480
Epoch [19/20] Train EMD: 69.4371 | Val EMD: 94.4233
  -> saved best model
Epoch [20/20] Train EMD: 55.3956 | Val EMD: 94.0476
  -> saved best model

In [36]:
from sklearn.model_selection import KFold
import numpy as np
import torch

K = 5

kf = KFold(n_splits=K, shuffle=True, random_state=42)
num_epochs = 100
patience = 30

fold_scores = []

for fold, (train_idx, val_idx) in enumerate(kf.split(df_labels)):
    print(f"\n{'='*40}")
    print(f"FOLD {fold + 1}/{K}")
    print(f"{'='*40}")

    # DataFrames
    fold_train_df = df_labels.iloc[train_idx].reset_index(drop=True)
    fold_val_df = df_labels.iloc[val_idx].reset_index(drop=True)

    print("Train:", len(fold_train_df))
    print("Val:", len(fold_val_df))

    train_dataset = SoilDataset(TRAIN_IMG_PATH, fold_train_df, train_transform)
    val_dataset = SoilDataset(TRAIN_IMG_PATH, fold_val_df, test_val_transform)
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2,
        pin_memory=True,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=1, shuffle=False, num_workers=2, pin_memory=True
    )

    model = SoilModel().to(device)

    for param in model.backbone.parameters():
        param.requires_grad = False

    for param in model.backbone.features[-2:].parameters():
        param.requires_grad = True
    
    optimizer = torch.optim.AdamW(
        [
            {
                "params": model.backbone.features[-2:].parameters(),
                "lr": 1e-5
            },
            {
                "params": model.metadata_net.parameters(),
                "lr": 1e-3
            },
            {
                "params": model.attention.parameters(),
                "lr": 1e-3
            },
            {
                "params": model.head.parameters(),
                "lr": 1e-3
            },
        ],
        weight_decay=1e-4
    )

    # Training
    best_val_loss = float("inf")
    
    for epoch in range(num_epochs):
        train_loss = train_one_epoch(model, train_loader, optimizer, device)
        val_loss = validate(model, val_loader, device)

        print(
            f"Fold {fold+1} | "
            f"Epoch [{epoch+1}/{num_epochs}] "
            f"Train: {train_loss:.4f} | "
            f"Val: {val_loss:.4f}"
        )
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
            torch.save(model.state_dict(), f"best_fold_{fold+1}.pth")
            print("  -> saved best model")
        else:
            epochs_without_improvement += 1
        if epochs_without_improvement >= patience:
            print(
                f"  -> Early stopping at epoch {epoch+1}"
            )
            break

    fold_scores.append(best_val_loss)
    print(f"Fold {fold+1} BEST EMD: " f"{best_val_loss:.4f}")

========================================
FOLD 1/5
========================================
Train: 19
Val: 5
Fold 1 | Epoch [1/100] Train: 92.5395 | Val: 116.6181
  -> saved best model
Fold 1 | Epoch [2/100] Train: 82.0866 | Val: 106.6473
  -> saved best model
Fold 1 | Epoch [3/100] Train: 81.4161 | Val: 107.8829
Fold 1 | Epoch [4/100] Train: 84.8719 | Val: 111.0751
Fold 1 | Epoch [5/100] Train: 86.8687 | Val: 114.5045
Fold 1 | Epoch [6/100] Train: 78.3333 | Val: 112.3193
Fold 1 | Epoch [7/100] Train: 75.2466 | Val: 110.9502
Fold 1 | Epoch [8/100] Train: 70.7397 | Val: 107.7640
Fold 1 | Epoch [9/100] Train: 65.5568 | Val: 108.3543
Fold 1 | Epoch [10/100] Train: 63.1866 | Val: 107.4439
Fold 1 | Epoch [11/100] Train: 64.8290 | Val: 96.8818
  -> saved best model
Fold 1 | Epoch [12/100] Train: 53.7188 | Val: 84.3869
  -> saved best model
Fold 1 | Epoch [13/100] Train: 60.0419 | Val: 65.9933
  -> saved best model
Fold 1 | Epoch [14/100] Train: 49.3757 | Val: 59.4269
  -> saved best model
Fold 1 | Epoch [15/100] Train: 40.2562 | Val: 72.3120
Fold 1 | Epoch [16/100] Train: 45.2040 | Val: 82.4878
Fold 1 | Epoch [17/100] Train: 44.4232 | Val: 81.9032
Fold 1 | Epoch [18/100] Train: 45.6973 | Val: 81.2568
Fold 1 | Epoch [19/100] Train: 45.0159 | Val: 81.2440
Fold 1 | Epoch [20/100] Train: 45.5985 | Val: 84.1063
Fold 1 | Epoch [21/100] Train: 49.4755 | Val: 62.1514
Fold 1 | Epoch [22/100] Train: 38.1966 | Val: 65.8895
Fold 1 | Epoch [23/100] Train: 34.2258 | Val: 64.0919
Fold 1 | Epoch [24/100] Train: 40.2007 | Val: 70.1600
Fold 1 | Epoch [25/100] Train: 41.7698 | Val: 65.9603
Fold 1 | Epoch [26/100] Train: 49.3948 | Val: 81.0706
Fold 1 | Epoch [27/100] Train: 36.1712 | Val: 84.5579
Fold 1 | Epoch [28/100] Train: 38.5809 | Val: 71.0691
Fold 1 | Epoch [29/100] Train: 43.4696 | Val: 74.2395
Fold 1 | Epoch [30/100] Train: 37.4240 | Val: 70.0053
Fold 1 | Epoch [31/100] Train: 39.4025 | Val: 65.0449
Fold 1 | Epoch [32/100] Train: 44.1246 | Val: 56.6980
  -> saved best model
Fold 1 | Epoch [33/100] Train: 36.4262 | Val: 54.8066
  -> saved best model
Fold 1 | Epoch [34/100] Train: 40.5360 | Val: 50.8663
  -> saved best model
Fold 1 | Epoch [35/100] Train: 39.0505 | Val: 45.1090
  -> saved best model
Fold 1 | Epoch [36/100] Train: 39.2432 | Val: 52.4232
Fold 1 | Epoch [37/100] Train: 36.1791 | Val: 38.8509
  -> saved best model
Fold 1 | Epoch [38/100] Train: 36.1554 | Val: 39.7879
Fold 1 | Epoch [39/100] Train: 40.8979 | Val: 43.8292
Fold 1 | Epoch [40/100] Train: 32.2518 | Val: 44.8593
Fold 1 | Epoch [41/100] Train: 34.3209 | Val: 51.0874
Fold 1 | Epoch [42/100] Train: 47.4998 | Val: 51.9456
Fold 1 | Epoch [43/100] Train: 34.5963 | Val: 40.2577
Fold 1 | Epoch [44/100] Train: 30.1772 | Val: 45.0867
Fold 1 | Epoch [45/100] Train: 39.9362 | Val: 38.5664
  -> saved best model
Fold 1 | Epoch [46/100] Train: 36.9932 | Val: 43.6653
Fold 1 | Epoch [47/100] Train: 31.5157 | Val: 40.8602
Fold 1 | Epoch [48/100] Train: 37.4578 | Val: 55.9866
Fold 1 | Epoch [49/100] Train: 31.4952 | Val: 43.2894
Fold 1 | Epoch [50/100] Train: 40.8178 | Val: 44.0190
Fold 1 | Epoch [51/100] Train: 32.3679 | Val: 50.2351
Fold 1 | Epoch [52/100] Train: 35.7446 | Val: 43.5791
Fold 1 | Epoch [53/100] Train: 30.5797 | Val: 51.4204
Fold 1 | Epoch [54/100] Train: 32.3665 | Val: 46.2961
Fold 1 | Epoch [55/100] Train: 29.8252 | Val: 47.2800
Fold 1 | Epoch [56/100] Train: 30.7305 | Val: 45.4046
Fold 1 | Epoch [57/100] Train: 25.7067 | Val: 51.1288
Fold 1 | Epoch [58/100] Train: 30.8455 | Val: 46.3971
Fold 1 | Epoch [59/100] Train: 32.3290 | Val: 54.5377
Fold 1 | Epoch [60/100] Train: 27.8189 | Val: 50.1001
Fold 1 | Epoch [61/100] Train: 24.0844 | Val: 57.8668
Fold 1 | Epoch [62/100] Train: 32.0728 | Val: 45.9751
Fold 1 | Epoch [63/100] Train: 23.7684 | Val: 42.7858
Fold 1 | Epoch [64/100] Train: 20.6310 | Val: 45.2083
Fold 1 | Epoch [65/100] Train: 25.0880 | Val: 47.9703
Fold 1 | Epoch [66/100] Train: 23.5012 | Val: 50.6581
Fold 1 | Epoch [67/100] Train: 28.9026 | Val: 56.8649
Fold 1 | Epoch [68/100] Train: 35.8713 | Val: 43.2275
Fold 1 | Epoch [69/100] Train: 31.0430 | Val: 56.1260
Fold 1 | Epoch [70/100] Train: 22.6888 | Val: 28.6428
  -> saved best model
Fold 1 | Epoch [71/100] Train: 26.9665 | Val: 48.6228
Fold 1 | Epoch [72/100] Train: 21.5292 | Val: 37.8740
Fold 1 | Epoch [73/100] Train: 28.8684 | Val: 44.6054
Fold 1 | Epoch [74/100] Train: 31.8001 | Val: 52.0035
Fold 1 | Epoch [75/100] Train: 23.9591 | Val: 52.1643
Fold 1 | Epoch [76/100] Train: 23.5784 | Val: 48.4290
Fold 1 | Epoch [77/100] Train: 23.7464 | Val: 53.4497
Fold 1 | Epoch [78/100] Train: 25.2407 | Val: 36.0470
Fold 1 | Epoch [79/100] Train: 24.5968 | Val: 33.7259
Fold 1 | Epoch [80/100] Train: 21.1651 | Val: 34.6610
Fold 1 | Epoch [81/100] Train: 24.1431 | Val: 41.9195
Fold 1 | Epoch [82/100] Train: 23.9513 | Val: 51.1034
Fold 1 | Epoch [83/100] Train: 23.9131 | Val: 39.5603
Fold 1 | Epoch [84/100] Train: 23.0581 | Val: 44.2477
Fold 1 | Epoch [85/100] Train: 21.6649 | Val: 52.9125
Fold 1 | Epoch [86/100] Train: 30.1037 | Val: 34.4480
Fold 1 | Epoch [87/100] Train: 22.5432 | Val: 40.1651
Fold 1 | Epoch [88/100] Train: 24.9469 | Val: 38.7665
Fold 1 | Epoch [89/100] Train: 30.0375 | Val: 34.0576
Fold 1 | Epoch [90/100] Train: 23.8518 | Val: 51.0533
Fold 1 | Epoch [91/100] Train: 24.3567 | Val: 32.2336
Fold 1 | Epoch [92/100] Train: 25.3923 | Val: 25.5813
  -> saved best model
Fold 1 | Epoch [93/100] Train: 24.2670 | Val: 37.5403
Fold 1 | Epoch [94/100] Train: 25.9269 | Val: 41.7632
Fold 1 | Epoch [95/100] Train: 21.7606 | Val: 51.5129
Fold 1 | Epoch [96/100] Train: 24.5548 | Val: 71.6631
Fold 1 | Epoch [97/100] Train: 22.1698 | Val: 80.9149
Fold 1 | Epoch [98/100] Train: 31.6200 | Val: 82.2859
Fold 1 | Epoch [99/100] Train: 19.4915 | Val: 67.7723
Fold 1 | Epoch [100/100] Train: 19.1853 | Val: 71.8633
Fold 1 BEST EMD: 25.5813

========================================
FOLD 2/5
========================================
Train: 19
Val: 5
Fold 2 | Epoch [1/100] Train: 95.2116 | Val: 76.4705
  -> saved best model
Fold 2 | Epoch [2/100] Train: 77.8167 | Val: 54.0841
  -> saved best model
Fold 2 | Epoch [3/100] Train: 64.3518 | Val: 49.7550
  -> saved best model
Fold 2 | Epoch [4/100] Train: 52.3691 | Val: 88.5007
Fold 2 | Epoch [5/100] Train: 77.9145 | Val: 75.7826
Fold 2 | Epoch [6/100] Train: 55.0494 | Val: 65.0359
Fold 2 | Epoch [7/100] Train: 75.8865 | Val: 55.0782
Fold 2 | Epoch [8/100] Train: 54.7217 | Val: 66.7726
Fold 2 | Epoch [9/100] Train: 46.8199 | Val: 70.4636
Fold 2 | Epoch [10/100] Train: 46.9022 | Val: 59.0204
Fold 2 | Epoch [11/100] Train: 60.3378 | Val: 89.7852
Fold 2 | Epoch [12/100] Train: 69.8049 | Val: 80.1528
Fold 2 | Epoch [13/100] Train: 63.1039 | Val: 72.2720
Fold 2 | Epoch [14/100] Train: 55.3419 | Val: 75.8957
Fold 2 | Epoch [15/100] Train: 40.1877 | Val: 63.2336
Fold 2 | Epoch [16/100] Train: 49.2816 | Val: 51.0481
Fold 2 | Epoch [17/100] Train: 57.9063 | Val: 57.4454
Fold 2 | Epoch [18/100] Train: 53.6524 | Val: 68.8589
Fold 2 | Epoch [19/100] Train: 56.7723 | Val: 74.9772
Fold 2 | Epoch [20/100] Train: 40.5313 | Val: 76.7870
Fold 2 | Epoch [21/100] Train: 34.9263 | Val: 74.7319
Fold 2 | Epoch [22/100] Train: 43.6981 | Val: 65.4611
Fold 2 | Epoch [23/100] Train: 39.0693 | Val: 77.4728
Fold 2 | Epoch [24/100] Train: 34.6414 | Val: 71.4225
Fold 2 | Epoch [25/100] Train: 36.9683 | Val: 63.8392
Fold 2 | Epoch [26/100] Train: 38.4969 | Val: 63.2621
Fold 2 | Epoch [27/100] Train: 45.8577 | Val: 74.2669
Fold 2 | Epoch [28/100] Train: 45.5053 | Val: 76.2521
Fold 2 | Epoch [29/100] Train: 47.6623 | Val: 89.2516
Fold 2 | Epoch [30/100] Train: 38.3628 | Val: 70.5748
Fold 2 | Epoch [31/100] Train: 40.2950 | Val: 74.5409
Fold 2 | Epoch [32/100] Train: 35.9578 | Val: 52.1056
Fold 2 | Epoch [33/100] Train: 42.4467 | Val: 49.0645
  -> saved best model
Fold 2 | Epoch [34/100] Train: 28.9024 | Val: 50.9036
Fold 2 | Epoch [35/100] Train: 32.4015 | Val: 49.0141
  -> saved best model
Fold 2 | Epoch [36/100] Train: 32.9730 | Val: 70.8733
Fold 2 | Epoch [37/100] Train: 38.8356 | Val: 69.6090
Fold 2 | Epoch [38/100] Train: 48.1204 | Val: 57.6373
Fold 2 | Epoch [39/100] Train: 37.3001 | Val: 55.2295
Fold 2 | Epoch [40/100] Train: 47.5507 | Val: 59.7432
Fold 2 | Epoch [41/100] Train: 27.2560 | Val: 57.7643
Fold 2 | Epoch [42/100] Train: 54.2990 | Val: 52.2941
Fold 2 | Epoch [43/100] Train: 42.3966 | Val: 69.2813
Fold 2 | Epoch [44/100] Train: 29.5824 | Val: 77.9266
Fold 2 | Epoch [45/100] Train: 37.8014 | Val: 68.4424
Fold 2 | Epoch [46/100] Train: 31.8136 | Val: 83.9195
Fold 2 | Epoch [47/100] Train: 36.7195 | Val: 76.0310
Fold 2 | Epoch [48/100] Train: 31.8649 | Val: 78.4369
Fold 2 | Epoch [49/100] Train: 31.6034 | Val: 62.4998
Fold 2 | Epoch [50/100] Train: 32.9966 | Val: 54.2753
Fold 2 | Epoch [51/100] Train: 43.3371 | Val: 61.5144
Fold 2 | Epoch [52/100] Train: 31.8903 | Val: 55.5239
Fold 2 | Epoch [53/100] Train: 49.5498 | Val: 73.3507
Fold 2 | Epoch [54/100] Train: 44.9949 | Val: 72.3661
Fold 2 | Epoch [55/100] Train: 31.5025 | Val: 79.8774
Fold 2 | Epoch [56/100] Train: 32.0029 | Val: 84.4379
Fold 2 | Epoch [57/100] Train: 36.6922 | Val: 67.3876
Fold 2 | Epoch [58/100] Train: 31.8813 | Val: 82.0311
Fold 2 | Epoch [59/100] Train: 40.0800 | Val: 90.8400
Fold 2 | Epoch [60/100] Train: 41.8811 | Val: 75.6413
Fold 2 | Epoch [61/100] Train: 38.5268 | Val: 55.2106
Fold 2 | Epoch [62/100] Train: 30.6791 | Val: 74.8034
Fold 2 | Epoch [63/100] Train: 31.7417 | Val: 75.7475
Fold 2 | Epoch [64/100] Train: 41.1063 | Val: 77.1724
Fold 2 | Epoch [65/100] Train: 30.9031 | Val: 88.2891
  -> Early stopping at epoch 65
Fold 2 BEST EMD: 49.0141

========================================
FOLD 3/5
========================================
Train: 19
Val: 5
Fold 3 | Epoch [1/100] Train: 100.6912 | Val: 75.8807
  -> saved best model
Fold 3 | Epoch [2/100] Train: 82.3459 | Val: 88.9764
Fold 3 | Epoch [3/100] Train: 66.6944 | Val: 77.7294
Fold 3 | Epoch [4/100] Train: 66.1372 | Val: 93.2207
Fold 3 | Epoch [5/100] Train: 72.9390 | Val: 88.8483
Fold 3 | Epoch [6/100] Train: 86.4692 | Val: 73.0334
  -> saved best model
Fold 3 | Epoch [7/100] Train: 62.2267 | Val: 76.2432
Fold 3 | Epoch [8/100] Train: 41.7478 | Val: 109.5732
Fold 3 | Epoch [9/100] Train: 58.5617 | Val: 90.9845
Fold 3 | Epoch [10/100] Train: 45.1876 | Val: 82.2290
Fold 3 | Epoch [11/100] Train: 74.0694 | Val: 87.1128
Fold 3 | Epoch [12/100] Train: 54.0638 | Val: 84.0511
Fold 3 | Epoch [13/100] Train: 42.8066 | Val: 90.0823
Fold 3 | Epoch [14/100] Train: 42.5579 | Val: 87.1461
Fold 3 | Epoch [15/100] Train: 44.1685 | Val: 82.9315
Fold 3 | Epoch [16/100] Train: 62.8487 | Val: 82.3339
Fold 3 | Epoch [17/100] Train: 55.0968 | Val: 74.3247
Fold 3 | Epoch [18/100] Train: 61.7317 | Val: 94.2402
Fold 3 | Epoch [19/100] Train: 35.6960 | Val: 82.5425
Fold 3 | Epoch [20/100] Train: 42.1973 | Val: 83.7641
Fold 3 | Epoch [21/100] Train: 46.6992 | Val: 77.1500
Fold 3 | Epoch [22/100] Train: 54.4082 | Val: 67.5230
  -> saved best model
Fold 3 | Epoch [23/100] Train: 38.0754 | Val: 92.5273
Fold 3 | Epoch [24/100] Train: 46.8285 | Val: 79.0617
Fold 3 | Epoch [25/100] Train: 43.6708 | Val: 82.2828
Fold 3 | Epoch [26/100] Train: 47.8669 | Val: 93.1158
Fold 3 | Epoch [27/100] Train: 58.1073 | Val: 77.3687
Fold 3 | Epoch [28/100] Train: 41.5113 | Val: 83.9392
Fold 3 | Epoch [29/100] Train: 36.7227 | Val: 72.7526
Fold 3 | Epoch [30/100] Train: 42.6472 | Val: 78.8529
Fold 3 | Epoch [31/100] Train: 35.7727 | Val: 72.0366
Fold 3 | Epoch [32/100] Train: 37.3816 | Val: 75.8042
Fold 3 | Epoch [33/100] Train: 34.6517 | Val: 80.6848
Fold 3 | Epoch [34/100] Train: 40.1658 | Val: 78.0157
Fold 3 | Epoch [35/100] Train: 40.5045 | Val: 82.9029
Fold 3 | Epoch [36/100] Train: 26.7164 | Val: 80.9403
Fold 3 | Epoch [37/100] Train: 32.9032 | Val: 69.1515
Fold 3 | Epoch [38/100] Train: 27.9444 | Val: 82.7234
Fold 3 | Epoch [39/100] Train: 40.9527 | Val: 86.0174
Fold 3 | Epoch [40/100] Train: 29.6921 | Val: 77.6839
Fold 3 | Epoch [41/100] Train: 37.3206 | Val: 82.5112
Fold 3 | Epoch [42/100] Train: 32.0377 | Val: 80.3485
Fold 3 | Epoch [43/100] Train: 26.7792 | Val: 86.0512
Fold 3 | Epoch [44/100] Train: 36.8724 | Val: 82.1981
Fold 3 | Epoch [45/100] Train: 29.8341 | Val: 78.8742
Fold 3 | Epoch [46/100] Train: 30.8598 | Val: 80.3492
Fold 3 | Epoch [47/100] Train: 27.1529 | Val: 81.4065
Fold 3 | Epoch [48/100] Train: 29.9525 | Val: 73.5235
Fold 3 | Epoch [49/100] Train: 41.1862 | Val: 67.7093
Fold 3 | Epoch [50/100] Train: 32.8461 | Val: 74.1866
Fold 3 | Epoch [51/100] Train: 21.9285 | Val: 81.2545
Fold 3 | Epoch [52/100] Train: 36.9515 | Val: 79.8226
  -> Early stopping at epoch 52
Fold 3 BEST EMD: 67.5230

========================================
FOLD 4/5
========================================
Train: 19
Val: 5
Fold 4 | Epoch [1/100] Train: 84.7402 | Val: 106.0816
  -> saved best model
Fold 4 | Epoch [2/100] Train: 75.6180 | Val: 112.4453
Fold 4 | Epoch [3/100] Train: 76.2788 | Val: 110.6051
Fold 4 | Epoch [4/100] Train: 80.7054 | Val: 115.6629
Fold 4 | Epoch [5/100] Train: 76.7828 | Val: 109.5493
Fold 4 | Epoch [6/100] Train: 84.8835 | Val: 109.2937
Fold 4 | Epoch [7/100] Train: 81.2296 | Val: 114.5244
Fold 4 | Epoch [8/100] Train: 79.3591 | Val: 110.4915
Fold 4 | Epoch [9/100] Train: 76.1764 | Val: 119.6161
Fold 4 | Epoch [10/100] Train: 77.8085 | Val: 115.6755
Fold 4 | Epoch [11/100] Train: 64.3506 | Val: 110.9432
Fold 4 | Epoch [12/100] Train: 73.5013 | Val: 111.1158
Fold 4 | Epoch [13/100] Train: 70.4006 | Val: 104.8004
  -> saved best model
Fold 4 | Epoch [14/100] Train: 58.5325 | Val: 98.1619
  -> saved best model
Fold 4 | Epoch [15/100] Train: 59.4712 | Val: 86.8858
  -> saved best model
Fold 4 | Epoch [16/100] Train: 53.4662 | Val: 62.6224
  -> saved best model
Fold 4 | Epoch [17/100] Train: 57.2743 | Val: 45.7861
  -> saved best model
Fold 4 | Epoch [18/100] Train: 55.6020 | Val: 63.3282
Fold 4 | Epoch [19/100] Train: 56.7167 | Val: 53.8619
Fold 4 | Epoch [20/100] Train: 55.3588 | Val: 47.0663
Fold 4 | Epoch [21/100] Train: 44.8115 | Val: 40.1741
  -> saved best model
Fold 4 | Epoch [22/100] Train: 39.9385 | Val: 49.2246
Fold 4 | Epoch [23/100] Train: 46.3973 | Val: 67.7984
Fold 4 | Epoch [24/100] Train: 41.7362 | Val: 67.0002
Fold 4 | Epoch [25/100] Train: 39.7124 | Val: 59.1150
Fold 4 | Epoch [26/100] Train: 47.4660 | Val: 49.7487
Fold 4 | Epoch [27/100] Train: 45.5862 | Val: 52.5851
Fold 4 | Epoch [28/100] Train: 42.9820 | Val: 58.4574
Fold 4 | Epoch [29/100] Train: 41.1883 | Val: 53.1821
Fold 4 | Epoch [30/100] Train: 49.0136 | Val: 54.6071
Fold 4 | Epoch [31/100] Train: 40.1979 | Val: 57.6466
Fold 4 | Epoch [32/100] Train: 44.7571 | Val: 56.7824
Fold 4 | Epoch [33/100] Train: 39.9222 | Val: 57.9271
Fold 4 | Epoch [34/100] Train: 32.5512 | Val: 54.7926
Fold 4 | Epoch [35/100] Train: 42.3722 | Val: 61.7105
Fold 4 | Epoch [36/100] Train: 34.9425 | Val: 62.8081
Fold 4 | Epoch [37/100] Train: 34.5634 | Val: 78.2610
Fold 4 | Epoch [38/100] Train: 38.8840 | Val: 66.4264
Fold 4 | Epoch [39/100] Train: 38.0794 | Val: 64.4559
Fold 4 | Epoch [40/100] Train: 38.2455 | Val: 74.4758
Fold 4 | Epoch [41/100] Train: 41.4698 | Val: 87.5770
Fold 4 | Epoch [42/100] Train: 35.3827 | Val: 86.6122
Fold 4 | Epoch [43/100] Train: 39.6345 | Val: 68.4096
Fold 4 | Epoch [44/100] Train: 34.1519 | Val: 72.7607
Fold 4 | Epoch [45/100] Train: 29.0305 | Val: 72.1104
Fold 4 | Epoch [46/100] Train: 38.0146 | Val: 80.1602
Fold 4 | Epoch [47/100] Train: 48.6284 | Val: 67.4067
Fold 4 | Epoch [48/100] Train: 33.5068 | Val: 69.9508
Fold 4 | Epoch [49/100] Train: 36.8804 | Val: 83.0444
Fold 4 | Epoch [50/100] Train: 36.6222 | Val: 67.8557
Fold 4 | Epoch [51/100] Train: 34.5849 | Val: 65.5300
  -> Early stopping at epoch 51
Fold 4 BEST EMD: 40.1741

========================================
FOLD 5/5
========================================
Train: 20
Val: 4
Fold 5 | Epoch [1/100] Train: 94.6351 | Val: 100.8985
  -> saved best model
Fold 5 | Epoch [2/100] Train: 91.5817 | Val: 100.0340
  -> saved best model
Fold 5 | Epoch [3/100] Train: 81.4550 | Val: 89.2766
  -> saved best model
Fold 5 | Epoch [4/100] Train: 74.0785 | Val: 64.7531
  -> saved best model
Fold 5 | Epoch [5/100] Train: 54.9652 | Val: 56.8446
  -> saved best model
Fold 5 | Epoch [6/100] Train: 54.1908 | Val: 55.5042
  -> saved best model
Fold 5 | Epoch [7/100] Train: 55.7365 | Val: 55.5102
Fold 5 | Epoch [8/100] Train: 50.7210 | Val: 81.5854
Fold 5 | Epoch [9/100] Train: 55.3136 | Val: 41.8386
  -> saved best model
Fold 5 | Epoch [10/100] Train: 38.4229 | Val: 52.7050
Fold 5 | Epoch [11/100] Train: 50.8699 | Val: 65.6485
Fold 5 | Epoch [12/100] Train: 45.3090 | Val: 71.2422
Fold 5 | Epoch [13/100] Train: 56.6203 | Val: 68.0196
Fold 5 | Epoch [14/100] Train: 57.2683 | Val: 70.2598
Fold 5 | Epoch [15/100] Train: 41.8291 | Val: 46.5631
Fold 5 | Epoch [16/100] Train: 53.5978 | Val: 65.6809
Fold 5 | Epoch [17/100] Train: 43.8013 | Val: 66.8254
Fold 5 | Epoch [18/100] Train: 38.1434 | Val: 62.1749
Fold 5 | Epoch [19/100] Train: 42.6396 | Val: 73.1457
Fold 5 | Epoch [20/100] Train: 33.2366 | Val: 57.3434
Fold 5 | Epoch [21/100] Train: 44.9515 | Val: 68.9981
Fold 5 | Epoch [22/100] Train: 33.6933 | Val: 32.3752
  -> saved best model
Fold 5 | Epoch [23/100] Train: 34.0348 | Val: 34.9233
Fold 5 | Epoch [24/100] Train: 33.9574 | Val: 39.1531
Fold 5 | Epoch [25/100] Train: 34.1046 | Val: 42.3665
Fold 5 | Epoch [26/100] Train: 39.3860 | Val: 43.3028
Fold 5 | Epoch [27/100] Train: 34.8672 | Val: 45.8184
Fold 5 | Epoch [28/100] Train: 31.6462 | Val: 52.9702
Fold 5 | Epoch [29/100] Train: 30.1430 | Val: 38.6597
Fold 5 | Epoch [30/100] Train: 41.2034 | Val: 44.9629
Fold 5 | Epoch [31/100] Train: 32.9711 | Val: 67.5010
Fold 5 | Epoch [32/100] Train: 39.2797 | Val: 43.6588
Fold 5 | Epoch [33/100] Train: 36.8760 | Val: 49.0863
Fold 5 | Epoch [34/100] Train: 42.2116 | Val: 53.5534
Fold 5 | Epoch [35/100] Train: 27.7129 | Val: 51.9877
Fold 5 | Epoch [36/100] Train: 31.0396 | Val: 55.0555
Fold 5 | Epoch [37/100] Train: 32.4221 | Val: 67.9160
Fold 5 | Epoch [38/100] Train: 34.0138 | Val: 67.4305
Fold 5 | Epoch [39/100] Train: 30.1982 | Val: 55.8777
Fold 5 | Epoch [40/100] Train: 36.2771 | Val: 51.7719
Fold 5 | Epoch [41/100] Train: 27.8663 | Val: 39.1269
Fold 5 | Epoch [42/100] Train: 25.2796 | Val: 38.0432
Fold 5 | Epoch [43/100] Train: 28.4623 | Val: 50.7836
Fold 5 | Epoch [44/100] Train: 28.7167 | Val: 39.8653
Fold 5 | Epoch [45/100] Train: 28.2740 | Val: 34.7106
Fold 5 | Epoch [46/100] Train: 27.1619 | Val: 35.7471
Fold 5 | Epoch [47/100] Train: 28.1379 | Val: 42.5573
Fold 5 | Epoch [48/100] Train: 30.8336 | Val: 74.5676
Fold 5 | Epoch [49/100] Train: 29.9504 | Val: 42.2374
Fold 5 | Epoch [50/100] Train: 28.9763 | Val: 34.6351
Fold 5 | Epoch [51/100] Train: 23.7699 | Val: 46.4760
Fold 5 | Epoch [52/100] Train: 29.1953 | Val: 47.4424
  -> Early stopping at epoch 52
Fold 5 BEST EMD: 32.3752

In [37]:
print("\n========== RESULTS ==========")

for i, score in enumerate(fold_scores):
    print(f"Fold {i+1}: {score:.4f}")

print(f"\nMean CV EMD: {np.mean(fold_scores):.4f}")
print(f"Std CV EMD:  {np.std(fold_scores):.4f}")

========== RESULTS ==========
Fold 1: 25.5813
Fold 2: 49.0141
Fold 3: 67.5230
Fold 4: 40.1741
Fold 5: 32.3752

Mean CV EMD: 42.9335
Std CV EMD:  14.5726

In [38]:
best_fold = fold_scores.index(min(fold_scores)) + 1
f"best_fold_{best_fold}.pth"

'best_fold_1.pth'

In [39]:
best_model_path = f"best_fold_{best_fold}.pth"
model.load_state_dict(torch.load(best_model_path, map_location=device))

model = model.to(device)

In [40]:
val_loss = validate(model, val_loader, device)

print(f"best model Val emd loss: {val_loss:.4f}")

best model Val emd loss: 41.8684

In [41]:
# val_dataset = SoilDataset(TRAIN_IMG_PATH, df_labels[20:], test_val_transform)

# val_loader = DataLoader(
#     val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True
# )

# val_loss = validate(model, val_loader, device)

# print(f"best model Val emd loss: {val_loss:.4f}")

In [42]:
predictions = []
sample_ids = []

model.eval()

with torch.no_grad():
    for batch in test_loader:
        images = batch["images"].to(device)
        metadata = batch["metadata"].to(device)
        logits = model(images, metadata)

        # logits -> probability mass
        mass = torch.softmax(logits, dim=-1)

        # mass -> cumulative distribution
        pred = torch.cumsum(mass, dim=-1) * 100.0
        predictions.extend(pred.cpu().numpy())
        sample_ids.extend(batch["sample_id"])

In [43]:
grain_columns = [
    "0.002",
    "0.0063",
    "0.02",
    "0.063",
    "0.2",
    "0.63",
    "2",
    "6.3",
    "20",
    "63",
    "200",
]

submission = pd.DataFrame(predictions, columns=grain_columns)
submission.insert(0, "sample_id", sample_ids)

In [44]:
submission.head(30)

,sample_id,0.002,0.0063,0.02,0.063,0.2,0.63,2,6.3,20,63,200
0,HPC_Airbus BS10-4bis7,1.153071,2.263537,5.897902,12.558755,16.492119,23.630116,35.941097,55.269791,83.891273,96.886459,100.000000
1,HPC_Airbus BS12-5bis8,0.428403,0.875555,2.774240,7.583308,9.722708,16.797125,30.413263,53.338520,82.756317,98.335991,100.000000
2,HPC_Airbus BS6-3,0.196917,0.406898,1.498247,5.077019,6.776134,12.372513,27.933853,52.637291,85.893188,98.969337,100.000015
3,HPC_Audorfring,0.224055,0.522473,1.865484,5.192183,7.135302,12.983903,29.655462,53.222847,84.964584,98.380699,100.000015
4,HPC_Kleinkummerfeld 18-3,0.436635,0.787310,2.588705,6.567339,9.042755,14.880693,29.293833,50.376850,84.568123,98.325478,99.999985
5,HPC_Kleinkummerfeld 2-2,0.092167,0.223792,0.934061,3.598850,5.109725,10.500716,27.305275,51.316666,86.409332,99.252831,100.000000
6,HPC_Kleinkummerfeld 2-3,0.114073,0.240290,1.029266,3.488774,5.024660,10.650358,26.321121,50.291718,86.134163,99.230034,100.000000
7,HPC_Kleinkummerfeld 9-4,0.343017,0.683571,2.047513,6.132883,8.316300,15.197253,29.630714,52.232582,83.052734,98.358284,100.000000
8,HPC_Muenster_BS6_9_0-10m,0.592725,0.991081,3.168360,6.769067,9.001747,13.809048,28.456482,50.907219,82.530991,98.581100,100.000000
9,HPC_Testfeld Lidl WHV,0.398133,0.756719,2.857838,6.897141,8.257607,12.155194,25.528416,51.405750,86.956161,99.057030,100.000000

In [45]:
# Clip numerical floating point errors
submission[grain_columns] = submission[grain_columns].clip(0, 100)

# Force final point to exactly 100
submission["200"] = 100.0

# Check monotonicity
values = submission[grain_columns].values

print("Monotonic:", np.all(np.diff(values, axis=1) >= 0))

print("Final = 100:", np.all(submission["200"].values == 100.0))

print("Number of samples:", len(submission))
submission.head()

Monotonic: True
Final = 100: True
Number of samples: 10

,sample_id,0.002,0.0063,0.02,0.063,0.2,0.63,2,6.3,20,63,200
0,HPC_Airbus BS10-4bis7,1.153071,2.263537,5.897902,12.558755,16.492119,23.630116,35.941097,55.269791,83.891273,96.886459,100.0
1,HPC_Airbus BS12-5bis8,0.428403,0.875555,2.774240,7.583308,9.722708,16.797125,30.413263,53.338520,82.756317,98.335991,100.0
2,HPC_Airbus BS6-3,0.196917,0.406898,1.498247,5.077019,6.776134,12.372513,27.933853,52.637291,85.893188,98.969337,100.0
3,HPC_Audorfring,0.224055,0.522473,1.865484,5.192183,7.135302,12.983903,29.655462,53.222847,84.964584,98.380699,100.0
4,HPC_Kleinkummerfeld 18-3,0.436635,0.787310,2.588705,6.567339,9.042755,14.880693,29.293833,50.376850,84.568123,98.325478,100.0

In [46]:
submission.to_csv("submission.csv", index=False)